IDIR = ../include

CC = g++
CEFLAG = -f -I$(IDIR)

DEPS = imprime.h
OBJS = imprime.o main.o
EXCC = el2




hola: hola.cpp
	g++ hola.cpp -o hola

// @ es el targuet.
// ^ son todas las dependencias.
// < la 1 dependencia.


// Variables importantes:
	//cc nombre compilador c
	//cxx nombre compilador c++
	//cpp compilador c
	//rm solo en unix y vale rm -f
	//LDFLAGS opciones para el linked
	//
